[2024-02-18T08:55:15.126+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: final_project.create_fact_schema manual__2024-02-18T08:55:13.724214+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
