[2024-02-18T09:00:38.643+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_time_dim_table manual__2024-02-18T08:55:13.724214+00:00 [queued]>
[2024-02-18T09:00:38.647+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_time_dim_table manual__2024-02-18T08:55:13.724214+00:00 [queued]>
[2024-02-18T09:00:38.647+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-02-18T09:00:38.653+0000] {taskinstance.py:2192} INFO - Executing <Task(LoadDimensionOperator): Load_time_dim_table> on 2024-02-18 08:55:13.724214+00:00
[2024-02-18T09:00:38.657+0000] {standard_task_runner.py:60} INFO - Started process 23395 to run task
[2024-02-18T09:00:38.659+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_time_dim_table', 'manual__2024-02-18T08:55:13.724214+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmplkmeysbe']
[2024-02-18T09:00:38.662+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask Load_time_dim_table
[2024-02-18T09:00:38.686+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Load_time_dim_table manual__2024-02-18T08:55:13.724214+00:00 [running]> on host 6b28116ad14a
[2024-02-18T09:00:38.721+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T08:55:13.724214+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T08:55:13.724214+00:00'
[2024-02-18T09:00:38.727+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-18T09:00:38.727+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-18T09:00:38.733+0000] {load_dimension.py:34} INFO - dim.dim_time is being inserted
[2024-02-18T09:00:38.737+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T09:00:42.674+0000] {sql.py:432} INFO - Running statement: 
        SELECT start_time, extract(hour from start_time), extract(day from start_time), extract(week from start_time), 
               extract(month from start_time), extract(year from start_time), extract(dayofweek from start_time)
        into dim.dim_time
        FROM staging.songplays
    , parameters: None
[2024-02-18T09:00:43.741+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/load_dimension.py", line 35, in execute
    redshift.run(self.sql.format(self.schema, self.table))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "staging.songplays" does not exist

[2024-02-18T09:00:43.750+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_project, task_id=Load_time_dim_table, execution_date=20240218T085513, start_date=20240218T090038, end_date=20240218T090043
[2024-02-18T09:00:43.758+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task Load_time_dim_table (relation "staging.songplays" does not exist
; 23395)
[2024-02-18T09:00:43.807+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T09:00:43.818+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
