[2024-02-18T08:53:05.628+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_songplays_fact_table manual__2024-02-18T08:50:10.099342+00:00 [queued]>
[2024-02-18T08:53:05.633+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_songplays_fact_table manual__2024-02-18T08:50:10.099342+00:00 [queued]>
[2024-02-18T08:53:05.634+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-02-18T08:53:05.641+0000] {taskinstance.py:2192} INFO - Executing <Task(LoadFactOperator): Load_songplays_fact_table> on 2024-02-18 08:50:10.099342+00:00
[2024-02-18T08:53:05.649+0000] {standard_task_runner.py:60} INFO - Started process 23225 to run task
[2024-02-18T08:53:05.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_songplays_fact_table', 'manual__2024-02-18T08:50:10.099342+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmp5n8rp507']
[2024-02-18T08:53:05.655+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask Load_songplays_fact_table
[2024-02-18T08:53:05.684+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Load_songplays_fact_table manual__2024-02-18T08:50:10.099342+00:00 [running]> on host 6b28116ad14a
[2024-02-18T08:53:05.726+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T08:50:10.099342+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T08:50:10.099342+00:00'
[2024-02-18T08:53:05.733+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-18T08:53:05.733+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-18T08:53:05.739+0000] {load_fact.py:34} INFO - fact.fact_song_plays is being inserted
[2024-02-18T08:53:05.744+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-18T08:53:11.015+0000] {sql.py:432} INFO - Running statement: 
        SELECT
            md5(events.sessionid || events.start_time) songplay_id,
            events.start_time, 
            events.userid, 
            events.level, 
            songs.song_id, 
            songs.artist_id, 
            events.sessionid, 
            events.location, 
            events.useragent
        into fact.fact_song_plays
        FROM (
            SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
            FROM staging_events
            WHERE page='NextSong'
        ) events
        LEFT JOIN staging_songs songs
        ON events.song = songs.title
            AND events.artist = songs.artist_name
            AND events.length = songs.duration
    , parameters: None
[2024-02-18T08:53:12.056+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/load_fact.py", line 35, in execute
    redshift.run(self.sql.format(self.schema, self.table))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidSchemaName: schema "fact" does not exist

[2024-02-18T08:53:12.065+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=final_project, task_id=Load_songplays_fact_table, execution_date=20240218T085010, start_date=20240218T085305, end_date=20240218T085312
[2024-02-18T08:53:12.074+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 60 for task Load_songplays_fact_table (schema "fact" does not exist
; 23225)
[2024-02-18T08:53:12.108+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T08:53:12.122+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
