[2024-02-19T09:27:50.460+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_user_dim_table manual__2024-02-19T09:25:05.177058+00:00 [queued]>
[2024-02-19T09:27:50.467+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_user_dim_table manual__2024-02-19T09:25:05.177058+00:00 [queued]>
[2024-02-19T09:27:50.467+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-02-19T09:27:50.475+0000] {taskinstance.py:2192} INFO - Executing <Task(LoadDimensionOperator): Load_user_dim_table> on 2024-02-19 09:25:05.177058+00:00
[2024-02-19T09:27:50.479+0000] {standard_task_runner.py:60} INFO - Started process 702 to run task
[2024-02-19T09:27:50.483+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_user_dim_table', 'manual__2024-02-19T09:25:05.177058+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpr6z4587t']
[2024-02-19T09:27:50.486+0000] {standard_task_runner.py:88} INFO - Job 161: Subtask Load_user_dim_table
[2024-02-19T09:27:50.523+0000] {task_command.py:423} INFO - Running <TaskInstance: final_project.Load_user_dim_table manual__2024-02-19T09:25:05.177058+00:00 [running]> on host b8bde2aaf906
[2024-02-19T09:27:50.569+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-19T09:25:05.177058+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-19T09:25:05.177058+00:00'
[2024-02-19T09:27:50.576+0000] {base.py:83} INFO - Using connection ID 'aws_credentials' for task execution.
[2024-02-19T09:27:50.577+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2024-02-19T09:27:50.584+0000] {load_dimension.py:36} INFO - dim.dim_users is being inserted
[2024-02-19T09:27:50.587+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T09:27:54.433+0000] {sql.py:432} INFO - Running statement: delete from dim.dim_users, parameters: None
[2024-02-19T09:27:55.520+0000] {sql.py:441} INFO - Rows affected: 104
[2024-02-19T09:27:57.451+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2024-02-19T09:28:01.629+0000] {sql.py:432} INFO - Running statement: 
    insert into dim.dim_users (userid, firstname, lastname, gender, level)
        SELECT distinct userid, firstname, lastname, gender, level
        FROM staging.staging_events
        WHERE page='NextSong'
    , parameters: None
[2024-02-19T09:28:02.900+0000] {sql.py:441} INFO - Rows affected: 104
[2024-02-19T09:28:04.648+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=final_project, task_id=Load_user_dim_table, execution_date=20240219T092505, start_date=20240219T092750, end_date=20240219T092804
[2024-02-19T09:28:04.691+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-19T09:28:04.703+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
